### ISSUE TITLE
Update for neovide 0.8

### ISSUE THREAD

**Issue by alexpetrean80** [chrisbouchard/neovide-nightly#1]
Neovide 0.8 has arrived in April 2022, but on copr the latest version is still 0.7.

**Comment by chrisbouchard** [comment]
Thanks for bringing this to my attention. The server that I was using to trigger nightly builds is currently out-of-commission. I'll get it back up and running at some point, but I'm busy in my personal life at the moment. I'll update this issue when I do.

**Comment by fkf6116** [comment]
Can I help take over?

I talked with Kay and the others in the discord server and they don't seem to mind

I have time and energy and a willingness to help
